kind: pipeline # 对象类型，有 pipeline、secret 和 signature 等类型
type: exec # 流水线类型，有 docker、kubernetes、exec、ssh 等类型
name: drone-golang-example

platform:
  os: linux
  arch: amd64

steps:
  - name: test & build
    environment:
      GOOS: linux
      GOARCH: amd64
      CGO_ENABLED: 0
    commands:
      - whoami
      # - cd /opt/drone-golang-example
      - echo "==== test ===="
      - go test
      - echo "==== build ===="
      - go build -o server
    # when:
    #   branch:
    #     - main

  - name: copy
    commands:
      - cp -rf ./server /opt/drone-golang-example/server
      - chown ubuntu:ubuntu /opt/drone-golang-example/server
      - chmod 755 /opt/drone-golang-example/server

  - name: stop
    commands:
      - sh scripts/stop.sh

  - name: run
    commands:
      - echo "==== run ===="
      - cd /opt/drone-golang-example
      - nohup ./server 2>&1 > web.log &
      - echo "running"
    # when:
    #   branch:
    #     - main

  - name: notify
    commands:
      - echo "failure"
    when:
      status:
        - failure

trigger:
  branch:
    - main
  event:
    - push
