kind: pipeline # 对象类型，有 pipeline、secret 和 signature 等类型
type: exec # 流水线类型，有 docker、kubernetes、exec、ssh 等类型
name: drone-golang-example

platform:
  os: linux
  arch: amd64

steps:
  - name: stop
    commands:
      - /bin/sh scripts/stop.sh

  - name: test & build
    environment:
      GOOS: linux
      GOARCH: amd64
      CGO_ENABLED: 0
    commands:
      - /usr/bin/whoami
      - echo "==== test ===="
      - /usr/local/go/bin/go test
      - echo "==== build ===="
      - /usr/local/go/bin/go build
    when:
      branch:
        - main

  - name: run
    commands:
      - echo "==== run ===="
      - /usr/bin/nohup ./drone-golang-example 2>&1 > web.log &
    when:
      branch:
        - main

  - name: notify
    commands:
      - echo "failure"
    when:
      status:
        - failure
