kind: pipeline # 对象类型，有 pipeline、secret 和 signature 等类型
type: exec # 流水线类型，有 docker、kubernetes、exec、ssh 等类型
name: linux_amd64

platform:
  os: linux
  arch: amd64

steps:
  - name: clone
    environment:
      GOOS: linux
      GOARCH: amd64
      CGO_ENABLED: 0
    commands:
      - go build
      - go test
