kind: pipeline # 对象类型，有 pipeline、secret 和 signature 等类型
type: exec # 流水线类型，有 docker、kubernetes、exec、ssh 等类型
name: drone-golang-example

platform:
  os: linux
  arch: amd64

steps:
  - name: test
    commands:
      - echo "==== test & build ===="
      - /usr/local/go/bin/go test
      - /usr/local/go/bin/go build -o server
  - name: run
    environment:
      GOOS: linux
      GOARCH: amd64
      CGO_ENABLED: 0
    commands:
      - echo "==== run ===="
      - ./server
