kind: pipeline # 对象类型，有 pipeline、secret 和 signature 等类型
type: exec # 流水线类型，有 docker、kubernetes、exec、ssh 等类型
name: drone-golang-example

platform:
  os: linux
  arch: amd64

steps:
  - name: copy
    commands:
      - cp -rf ./ /opt/drone-golang-example

  - name: stop
    commands:
      - sh scripts/stop.sh

  - name: test & build
    environment:
      GOOS: linux
      GOARCH: amd64
      CGO_ENABLED: 0
    commands:
      - whoami
      - cd /opt/drone-golang-example
      - echo "==== test ===="
      - go test
      - echo "==== build ===="
      - go build
    when:
      branch:
        - main

  - name: run
    commands:
      - echo "==== run ===="
      - cd /opt/drone-golang-example
      - nohup ./drone-golang-example 2>&1 > web.log &
    when:
      branch:
        - main

  - name: notify
    commands:
      - echo "failure"
    when:
      status:
        - failure
