kind: pipeline
type: docker
name: linux_amd64

environment:
  GOOS: linux
  GOARCH: amd64
  CGO_ENABLED: 0

steps:
  - name: build-linux-amd64
    image: alpine:latest
    commands:
      - make build
      - ./build/linux/amd64/hello-drone -h

  - name: notify
    image: alpine:latest
    commands:
      - echo "Done!"
    depends_on:
      - build-linux-amd64
