version: '3.3'

networks:
  monitor:
    driver: bridge

services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: always
    volumes:
      - type: 'bind'
        source: /etc/prometheus/prometheus.yml
        target: /etc/prometheus/prometheus.yml
        read_only: true
      - type: 'bind'
        source: /etc/prometheus/alert-rules.yml
        target: /etc/prometheus/alert-rules.yml
        read_only: true
      - /data/prometheus:/data/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/data/prometheus'
    ports:
      - '9090:9090'
    networks:
      - monitor
