kind: pipeline # 对象类型，还有 secret 和 signature 两种类型
type: docker # 流水线类型，还有 kubernetes、exec、ssh 等类型
name: linux_amd64

environment:
  GOOS: linux
  GOARCH: amd64
  CGO_ENABLED: 0

steps:
  - name: build-linux-amd64
    image: appleboy/drone-ssh # SSH 工具镜像
    commands:
      - make build
      - ./build/linux/amd64/hello-drone -h

  - name: notify
    image: alpine:latest
    commands:
      - echo "Done!"
    depends_on:
      - build-linux-amd64
